### ISSUE TITLE
Error occurred when issue logon ticket

### ISSUE THREAD

**Issue by alvin2guo** [danstutzman/sso_sap_demo#1]
I have done as blow:
1. cd sso_sap_demo-master/java
2. ./create_keystore.sh keystore1 verify1.der
file keystore1  and verify1.der have been produced.
3. ./issue_logon_ticket.sh ./keystore1 test 120
the error info:
java.security.NoSuchProviderException: SUN
	at java.security.KeyStore.getInstance(KeyStore.java:117)
	at com.sap.security.core.ticket.imp.Ticket.signTicket(Ticket.java:1266)
	at com.sap.security.core.ticket.imp.Ticket.create(Ticket.java:1145)
	at com.sap.security.core.ticket.imp.Ticket.main(Ticket.java:1747)
com.sap.security.api.ticket.TicketException: Security provider not configured.
	at com.sap.security.core.ticket.imp.Ticket.create(Ticket.java:1181)
	at com.sap.security.core.ticket.imp.Ticket.main(Ticket.java:1747)
Unknown provider.java.security.NoSuchProviderException: SUNException com.sap.security.api.ticket.TicketException: Security provider not configured. occured.

**Comment by danstutzman** [comment]
Thanks for the bug report but I'm choosing not to put further time into maintaining this software

**Comment by alvin2guo** [comment]
This problem caused by jdk version. Thanks!
